const pokedexTypes = {
  CHANGE_REGION: 'CHANGE_REGION',
  INITIAL_FETCH_STARTED: 'INITIAL_FETCH_STARTED',
  INITIAL_FETCH_FAILED: 'INITIAL_FETCH_FAILED',
  INITIAL_FETCH_SUCCESS: 'INITIAL_FETCH_SUCCESS',
  UPDATE_REGION: 'UPDATE_REGION'
}

export default pokedexTypes